---
title: "APM466 Assignment 1"
author: "Jiayue_Wu"
date: "2/6/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(readxl)
dirty <- read_excel("~/Desktop/APM466/bond_data.xlsx")
```




```{r}
names(dirty) <- c("ISIN", "ISSUE_DATE", "MATURITY_DATE", "COUPON", "2022-01-10", "2022-01-11", "2022-01-12", "2022-01-13", "2022-01-14", "2022-01-17", "2022-01-18", "2022-01-19", "2022-01-20", "2022-01-21")
```

```{r}
# get the index of the bond with maturity date I want.
m <- c()
date <- c("8/1/2022", "2/1/2023", "8/1/2023", "2/1/2024", "9/1/2024", "3/1/2025", "9/1/2025", "3/1/2026", "9/1/2026", "3/1/2027")
for (i in 1:10){
  m[i] <- which(dirty$MATURITY_DATE == date[i])[1]
}
# create a new data frame contain only the 10 bonds I want. 
data <-dirty[m,]
data$Name <- c( "CAN 0.25 Jul 31", "CAN 0.25 Jan 31", "CAN 0.25 Jul 31", "CAN 0.75 Jan 31", "CAN 1.5 Aug 31", "CAN 1.25 Feb 28", "CAN 0.5 Aug 31", "CAN 0.25 Feb 28", "CAN 1.0 Aug 31", "CAN 0.625 Feb 28")
```





```{r}
# coupon payment for semi-annual.
coupon <- data$COUPON * 1/2
# direct the price data we needed. 
Price <- data.frame(data[,c(5:14)])
```



```{r}
# create a vector storing spots rate calculated.
Spots <- c()
# create a loop for each date.
for (m in 1:10) {
  # create a vector storing spots rate for each bond on the m date.
  r <- c()
  # refer to the m date price
  P <- Price[m]
  # refer to each bond for the m date.
  for (i in 1:10){
    # if is the first bond, will record it directly to the r. 
    if (i == 1){
      r1 <- -2*log(P[i,]/(100*coupon[i] + 100))
      r[i] <- r1
    } 
    # case if not the first bond
    else{
      cpn <- 0 
      # calculate and cumulate the coupon price for date before maturity one.
      for (j in 1:(i-1)){
        cpn <- cpn + 100 * coupon[i] * exp(-r[j]*(0.5*j))
      }
     ri <- log((P[i,]-cpn)/(100*coupon[i] + 100))/((-1/2)*i)
     r[i] <- ri
   }
  }
  # store the spots rate I calculated in the Spots data frame.
  Spots <- as.data.frame(cbind(Spots, r))
}


x <- seq(0.5,5,0.5)
# draw the 10 dates' 5-year Spots rate curve. 
plot(x,Spots[,1],type="l", col="yellow",ylim = c(0.0065, 0.0172) ,xlab="Time to maturity (years)",ylab="Spots Rate", main =" Spots Curve (5 years)")
lines(x,Spots[,2],col="red")
lines(x,Spots[,3],col="grey")
lines(x,Spots[,4],col="blue")
lines(x,Spots[,5],col="black")
lines(x,Spots[,6],col="orange")
lines(x,Spots[,7],col="purple")
lines(x,Spots[,8],col="pink")
lines(x,Spots[,9],col="green")
lines(x,Spots[,10],col="darkblue")
legend("bottomright",data$Name,lty=c(1,1), lwd=c(2,2),cex=0.75, 
       col=c("yellow","red","grey","blue","black","orange","purple","pink","green", "darkblue"))
```





```{r}
# create a vector storing YTM calculated.
YTM <- c()
# create a loop for each date.
for (m in 1:10) {
  # create a vector storing ytm for each bond on the m date.
  yield <- c()
  for (j in 1:10) {
    P <- Price[m][j,]
    # refer to the m date price
    f.ytm = function(ytm){
    cpn <- NULL
    # calculate and cumulate the coupon price for date before maturity one.
    for (i in 1:j) {
      cpn[i] = 100*coupon[j]*exp(-ytm*(1/2)*i)
    }
      F = sum(cpn) + 100 * exp(-ytm*(1/2)*j) - P
    }
    solution = uniroot(f.ytm, interval=c(0,25))
    ytm = solution$root
    yield[j] <- ytm
  }
  # store the ytm I calculated in the YTM data frame.
  YTM <- as.data.frame(cbind(YTM, yield))
}

# draw the 10 dates' 5-year YTM curve. 
plot(x,YTM[,1],type="l", col="yellow",ylim = c(0.0065, 0.0172) ,xlab="Time to maturity (years)",ylab="yield to maturity", main ="Yield Curve (5 years)")
lines(x,YTM[,2],col="red")
lines(x,YTM[,3],col="grey")
lines(x,YTM[,4],col="blue")
lines(x,YTM[,5],col="black")
lines(x,YTM[,6],col="orange")
lines(x,YTM[,7],col="purple")
lines(x,YTM[,8],col="pink")
lines(x,YTM[,9],col="green")
lines(x,YTM[,10],col="darkblue")
legend("bottomright",data$Name, lty=c(1,1), lwd=c(2,2),cex=0.75,
       col=c("yellow","red","grey","blue","black","orange","purple","pink","green", "darkblue"))
```




```{r}
# create a vector storing forward rate calculated.
forward <- c()
# create a loop for each date.
for (j in 1:10) {
  # refer to the spots rate of j date.
  spot <- Spots[, j]
  r1 <- spot[2]
  # create a vector storing forward rate for each bond on the m date.
  f <- c()
  for (i in 2:5) {
    frate <- (spot[i*2]*i - r1)/(i - 1)
    f[i - 1] <- frate
  }
  # store the forward rate I calculated in the forward data frame.
  forward <- as.data.frame(cbind(forward, f))
}


# draw the 10 dates' 4 kinds 1-year forward curve. 
plot(seq(1,4),forward[,1],type="l", col="yellow", ylim = c(0.0132, 0.0188) ,xlab="Extra Years from year 1",ylab="forward Rate", main ="1-year Forward Rate Curve")
lines(seq(1,4),forward[,2],col="red")
lines(seq(1,4),forward[,3],col="grey")
lines(seq(1,4),forward[,4],col="blue")
lines(seq(1,4),forward[,5],col="black")
lines(seq(1,4),forward[,6],col="orange")
lines(seq(1,4),forward[,7],col="purple")
lines(seq(1,4),forward[,8],col="pink")
lines(seq(1,4),forward[,9],col="green")
lines(seq(1,4),forward[,10],col="darkblue")
legend("bottomright",data$Name,lty=c(1,1), lwd=c(2,2),cex=0.75,
       col=c("yellow","red","grey","blue","black","orange","purple","pink","green", "darkblue"))
```





```{r}
# create a vector storing daily log-returns of yield calculated.
yield_matrice <- c()

yield1 <- c()
yield2 <- c()
yield3 <- c()
yield4 <- c()
yield5 <- c()

for (i in c(1:9))
  {
  yield1[i] <- log(YTM[2,i]/YTM[2,i+1])
  yield2[i] <- log(YTM[4,i]/YTM[4,i+1])
  yield3[i] <- log(YTM[6,i]/YTM[6,i+1])
  yield4[i] <- log(YTM[8,i]/YTM[8,i+1])
  yield5[i] <- log(YTM[10,i]/YTM[10,i+1])
}

# store the daily log-returns of yield I calculated in the forward data frame.
yield_matrice <- as.data.frame(cbind(yield_matrice, yield1))
yield_matrice <- as.data.frame(cbind(yield_matrice, yield2))
yield_matrice <- as.data.frame(cbind(yield_matrice, yield3))
yield_matrice <- as.data.frame(cbind(yield_matrice, yield4))
yield_matrice <- as.data.frame(cbind(yield_matrice, yield5))
# calculate the covariance of the daily log-returns of yield calculated.
covariance_yield = cov(yield_matrice,yield_matrice)
knitr::kable(covariance_yield)

eigen(covariance_yield)
transpose
e1 <- round(eigen(covariance_yield)$values,8)
(explained <- e1/sum(e1))
```



```{r}
# create a vector storing daily log-returns of forward calculated.
forward_matrice <- c()

fwd_1 <- c()
fwd_2 <- c()
fwd_3 <- c()
fwd_4 <- c()

for(i in c(1:9))
{
  fwd_1[i]=log(forward[1,i]/forward[1,i+1])
  fwd_2[i]=log(forward[2,i]/forward[2,i+1])
  fwd_3[i]=log(forward[3,i]/forward[3,i+1])
  fwd_4[i]=log(forward[4,i]/forward[4,i+1])
}

# store the daily log-returns of forward I calculated in the forward data frame.
forward_matrice <- as.data.frame(cbind(forward_matrice, fwd_1))
forward_matrice <- as.data.frame(cbind(forward_matrice, fwd_2))
forward_matrice <- as.data.frame(cbind(forward_matrice, fwd_3))
forward_matrice <- as.data.frame(cbind(forward_matrice, fwd_4))
# calculate the covariance of the daily log-returns of forward calculated.
covariance_forward = cov(forward_matrice,forward_matrice)
knitr::kable(covariance_forward)
ev2 <- eigen(covariance_yield)$vectors
t(ev2)
```


```{r}
ev <- eigen(covariance_forward)$vectors
t(ev)
e2 <- eigen(covariance_forward)$values
(explained <- e2/sum(e2))
```






```{r}
# calaulate the eigenvalues and eigenvectors of the yield covariance matrice. 
eigen_yield <- eigen(covariance_yield,symmetric=TRUE,only.values = FALSE)
eigen_yield
# calaulate the eigenvalues and eigenvectors of the forward covariance matrice. 
eigen_forward <- eigen(covariance_forward,symmetric=TRUE,only.values = FALSE)
eigen_forward
```



